### ISSUE TITLE
make clean does not clean dependency information

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/bedrock2#10]
after updating today I got

2 kevix@ashryn ~/mit-plv/bedrock2 (git)-[master] % env EXPECTED_COQC_VERSION=8.8.0 make -j4                                                                                                                                          :(
make: *** No rule to make target '../riscv-coq/src/RiscvBitWidths.vo', needed by 'src/ExprImp.vo'.  Stop.

https://github.com/samuelgruetter/riscv-coq/commit/01f3196e6f15dea77beba34c582a572d1c921098 seems to have moved that file.

then I ran make clean and got the same thing again

then I ran git clean -dxf and make and then everything worked

**Comment by samuelgruetter** [comment]
I see two reasons why this could happen:
1) There's a certain kind of files that `make clean` should delete but doesn't delete. If that's the case, do you know what kind of file?
2) `make -j4` schedules stuff before `make depend` has run and ignores dependencies. I sometimes got similar errors as you when building with -j on a clean repo and the fix was to run `make depend && make -j4` instead.

**Comment by andres-erbsen** [comment]
I am pretty sure I tried without `-j4` and saw the same behavior.

**Comment by samuelgruetter** [comment]
To get the list of files that `make clean` removes (minus `.depend`), I ran this command:

```
find . -type f \( -name '*.glob' -o -name '*.vo' -o -name '*.aux' \) | sed -e 's/^\.\///g' | sort > tmp_find.txt
```

To get the list of files that `git clean -dxf` removes, I ran this command:
```
git clean -dxf --dry-run | sed -e 's/Would remove //g' | sort > tmp_gitclean.txt
```

The diff between these two lists doesn't contain anything interesting on my machine.
Next time you clean and recompile, could you please test these and let me know if the diff contains something interesting?

**Comment by andres-erbsen** [comment]
Thanks, will do.

**Comment by samuelgruetter** [comment]
In another project, I have `*.v.d` files, maybe you have such files in your repo too? Did you use another coqdep than me? A difference between 8.7 and 8.8?

**Comment by JasonGross** [comment]
Reading the makefile, I don't see how this could possibly happen unless you had a merge conflict or other local change in src/ExprImp.v *and* did something like `git reset --hard` in addition to `git clean`.

**Comment by andres-erbsen** [comment]
I think I figured out what happened: I had a stale `.depend` from earlier and it was not getting updated.
