### ISSUE TITLE
There should be a top-level build target to build bedrock2 without examples and without the bytedump test

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/bedrock2#106]
C.f. https://github.com/mit-plv/fiat-crypto/pull/587#issuecomment-537980638

It would be nice to not have to wait for the examples to build when I make fiat-crypto.  Also, it would be nice if I could skip things by running `make -t`; currently I can't because every single invocation of `make` tries to test bytedump behavior, which doesn't work when bytedump.vo is empty.

**Comment by samuelgruetter** [comment]
Addressed in https://github.com/mit-plv/bedrock2/commit/83679adf909d346f8ab7e5d249f057cda96f6f70, is that what you need?

And what do you need `make -t` for?

**Comment by JasonGross** [comment]
> Addressed in [83679ad](https://github.com/mit-plv/bedrock2/commit/83679adf909d346f8ab7e5d249f057cda96f6f70), is that what you need?

Yes, thanks!  (Though ideally there'd also be a target in the top-level makefile.  But if you don't want to do that, that's fine.)



> And what do you need `make -t` for?

Sometimes I'm really impatient and want to skip building bedrock all-together, on every subsequent build, because I'm not dealing with files that touch bedrock2. :-P

**Comment by samuelgruetter** [comment]
> Yes, thanks! (Though ideally there'd also be a target in the top-level makefile. But if you don't want to do that, that's fine.)

The toplevel Makefile [now](https://github.com/mit-plv/bedrock2/commit/1c32021ed0b20407b86e6bfb3e40fd5ce7dba7c1) provides `make bedrock2_noex` to build `bedrock2/bedrock2` without the examples.

**Comment by JasonGross** [comment]
This is fixed and can be closed now, right?

**Comment by samuelgruetter** [comment]
yes!
