### ISSUE TITLE
Travis should test this on CI

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/bedrock2#11]
The pre-req for getting this added to Coq's CI is to have this repo run continuous integration.  Please add a `.travis.yml` to test this against master and 8.8 (and any other branches you care about).  If you do that, I can add this to Coq's CI, and the bench.

**Comment by andres-erbsen** [comment]
Oops, I wrote a dupe with more explanation before reading this: https://github.com/mit-plv/bedrock2/issues/12
