### ISSUE TITLE
Travis spuriously uses Coq 8.4 instead of master

### ISSUE THREAD

**Issue by samuelgruetter** [mit-plv/bedrock2#123]
Here's a travis build log which is supposed to use Coq master, but uses Coq 8.4, it seems: https://travis-ci.com/mit-plv/bedrock2/jobs/269470042#L552

While another build with the same travis file succeeds: https://travis-ci.com/mit-plv/bedrock2/jobs/269472535#L512

For the moment, I'm classifying this as a spurious weirdness/no action needed, opening the issue just for the record in case it occurs again.

/cc @JasonGross

**Comment by JasonGross** [comment]
If you look carefully at the first log, you will note that `apt-get update` fails with error code 0 (which I think is a terrible mis-feature).  We have a script in fiat-crypto that wraps apt-get update and retries if it fails, and kills the build if it keeps failing.

**Comment by samuelgruetter** [comment]
Thanks for the explanation @JasonGross, I [copied](https://github.com/mit-plv/bedrock2/commit/186ca0559fad020f4a75200030a3f0df550571b2) what you do in fiat-crypto.
