### ISSUE TITLE
Semantics.parameters_ok instance for BasicC32Semantics

### ISSUE THREAD

**Issue by jadephilipoom** [mit-plv/bedrock2#151]
There's a `Semantics.parameters_ok` instance in `BasicC64Semantics`, but not for 32-bit. Is there a particular reason for this? Now that I'm adding 32-bit support to the fiat-crypto bedrock2 backend, it'd be nice to replace the placeholder axiom I'm currently using with a real proof.

**Comment by andres-erbsen** [comment]
The main 32-bit target right now is https://github.com/mit-plv/bedrock2/blob/master/bedrock2/src/bedrock2/FE310CSemantics.v#L57 and https://github.com/mit-plv/bedrock2/blob/master/end2end/src/end2end/Bedrock2SemanticsForKami.v#L27

But proving `parameters_ok` for the basic version if you wish should also be easy (try copy-pasting the 64-bit proof).
