### ISSUE TITLE
bedrock2.NotationsCustomEntry breaks Tactic Notation

### ISSUE THREAD

**Issue by samuelgruetter** [mit-plv/bedrock2#165]
When I `Require Import bedrock2.NotationsCustomEntry`, the command `Tactic Notation` stops working. Minimized:

```coq
Tactic Notation "foo1" constr(x) := idtac x. (* works *)

(* offending lines of bedrock2.NotationsCustomEntry: *)
Declare Custom Entry bedrock_expr.
Notation "'constr' : ( e )" := e (in custom bedrock_expr, e constr).

Tactic Notation "foo2" constr(x) := idtac x. (* syntax error *)
```

Might be related to https://github.com/coq/coq/issues/9633.

@andres-erbsen is there a way to make Tactic Notations work with `bedrock2.NotationsCustomEntry` in Coq 8.12?

**Comment by andres-erbsen** [comment]
@JasonGross can you help us out here?

**Comment by JasonGross** [comment]
Mention it on the bug report and ask @herbelin for a solution?  In the meantime, use `CONSTR` instead and be a bit dissatisfied?

**Comment by samuelgruetter** [comment]
Or how about `coq:(...)`?
Bedrock2 source code is sometimes shown to outside audience, and for them that might be even better than `constr:(...)`, just some marker that says "switch from bedrock2 source code back to Coq source code" seems like a fine explanation.

**Comment by herbelin** [comment]
Yes, this is an issue with `constr` becoming a keyword. No obvious preferred solution for it:
- either having keywords eventually local to custom entries
- or providing a notation modifier `foo not keyword` at users' own risk
- or having an `ident_or_keyword` entry to be used in the `Tactic Notation` syntax - see also this [comment](https://github.com/coq/coq/pull/13183#discussion_r503345749) at #13183
- or having camlp5 automatically recognize when it is safe to parse keywords in place of identifiers, ...)
- ...

**Comment by JasonGross** [comment]
> - either having keywords eventually local to custom entries

This one seems obviously good; is there any reason to share keywords between custom entries?


> - or having an ident_or_keyword entry to be used in the Tactic Notation syntax

Is there any reason to not do this one?

> - or providing a notation modifier foo not keyword at users' own risk

I think `foo ident or keyword` might be better here, no?
