### ISSUE TITLE
straightline_cleanup turns provable goal unprovable

### ISSUE THREAD

**Issue by bdiehs** [mit-plv/bedrock2#167]
In the following minimized example
```
Goal forall (T U : Type) (a b : T) (f g : T -> U), let c := f b in c = g a -> c = f b.
   Proof.
     intros.
     straightline_cleanup.
     auto.
   Abort.
```
an easily provable goal is turned unprovable because one of the needed hypotheses is cleared by `straightline_cleanup`.
More specifically, this pattern makes that happen
```
| H: ?x = ?v |- _ =>
    is_var x;
    lazymatch v with context[x] => fail | _ => idtac end;
    let x' := fresh x in
    rename x into x';
    simple refine (let x := v in _);
    change (x' = x) in H;
    symmetry in H;
    destruct H
```
@andres-erbsen @samuelgruetter

**Comment by samuelgruetter** [comment]
@andres-erbsen would you mind explaining what the above Ltac snippet is supposed to do/why you wrote it like this?

**Comment by JasonGross** [comment]
It looks like it's supposed to turn `x = v` into `x := v` when `x` is a variable.  The issue is that it doesn't check for `x` already having a body; you should assert also that `eval cbv delta [x] in x` fails after checking that `x` is a variable

**Comment by samuelgruetter** [comment]
Thanks Jason for the suggested fix! 
But why do we want to turn `x = v` into `x := v`? I understand the program logic creates many let bindings, but why would you want to turn user-made equalities into lets?

**Comment by andres-erbsen** [comment]
This was probably just a bad idea, but it helps computation do more simplifications in some places. I suspect there is still code that relies on it, so I am applying Jason's suggested fix.
