### ISSUE TITLE
ensure and test that return values are assigned left to right

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/bedrock2#18]
we do want them left-to-right, right?

**Comment by samuelgruetter** [comment]
yes!

**Comment by andres-erbsen** [comment]
Okay. In particular, we should check that the C pretty-printer also does this right.

**Comment by andres-erbsen** [comment]
FIxed; tests at https://github.com/mit-plv/bedrock2/blob/master/bedrock2/src/Examples/MultipleReturnValues.v#L25 and https://github.com/mit-plv/bedrock2/blob/master/bedrock2/src/Map/UnorderedList.v#L26
