### ISSUE TITLE
bedrock2.Syntax.parameters needs a better name

### ISSUE THREAD

**Issue by samuelgruetter** [mit-plv/bedrock2#19]

**Comment by andres-erbsen** [comment]
Why?

**Comment by samuelgruetter** [comment]
It's confusing to have so many types with the same name, and Coq will print the parameters of the last imported module as `parameters` rather than `MyModule.parameters`.

Would renaming them to `MyModule_parameters` work? In particular, would `StringNames` still work, or does it have to override `Syntax.parameters`?

**Comment by andres-erbsen** [comment]
I would instead recommend not importing the modules, but if changing the name really makes it for you, go for it.
