### ISSUE TITLE
Using multiple return values

### ISSUE THREAD

**Issue by RasmusHoldsbjergCSAU** [mit-plv/bedrock2#222]
I have been trying to write and use bedrock2 functions that return multiple values.

As a simple example, consider a function that just returns two values; 0 and 2.
The following compiles:
```
Definition test : bedrock_func :=
  let ret1 := "ret1" in
  let ret2 := "ret2" in
  ("test", ([]: list string, ([ret1; ret2]:list String.string), bedrock_func_body:(
  ret1 = coq:(0);
  ret2 = coq:(2)
))).

Instance spec_of_test : spec_of "test" := fnspec! "test" ~> v1 v2,
  { requires t m := True;
    ensures t' m' := t=t' /\ m=m' /\
      word.unsigned v1 = 0 /\
      word.unsigned v2 = 2 }.

Lemma test_correct : program_logic_goal_for_function! test.
Proof.
    repeat straightline; eexists; split; [cbv; eauto| do 2 eexists; auto].
Qed.
```
However, the behavior of returned values is confusing to me, when the function is called;
Consider a function that accepts an argument, x, calls test, and sets x equal to the second returned value:

```
Definition test_call : bedrock_func :=
    let x := "x" in
    let p := "p" in
    let q := "q" in
    let test := "test" in
    ("call", ([x], [] : list string, bedrock_func_body:(
        unpack! p, q  = test();
        x = q
    ))).

    Instance spec_of_call : spec_of "call" := fnspec! "call" x / (z : Z),
    { requires t m := True;
      ensures t' m' := t=t' /\ m=m' /\
        word.unsigned x = 2 }.

Lemma call_correct : program_logic_goal_for_function! test_call.
Proof.
    repeat straightline. straightline_call; auto. repeat straightline; do 3 (split; auto).
Abort.
```

The partial proof of call_correct leaves the goal `word.unsigned x2 = 2`, but no assumptions on x2.

If someone can clarify the intended use of return values and/or point out what I am doing wrong here, that would be very helpful.

I have looked at the example bedrock2Examples/MultipleReturnValues.v, but did not find it very illuminating. What kind of spec would it be possible to prove about addsub_test?

**Comment by RasmusHoldsbjergCSAU** [comment]
Silly me, test_call is supposed to be

```
Definition test_call : bedrock_func :=
    let x := "x" in
    let p := "p" in
    let q := "q" in
    let test := "test" in
    ("call", ([x], [] : list string, bedrock_func_body:(
        unpack! p, q  = test();
        store(x, q)
    ))).
```
I got the example working; sorry for the inconvenience.

**Comment by andres-erbsen** [comment]
I'm glad you figured out a solution that works for you. I think the following (untested) code should also work:

```coq
Definition test_call : bedrock_func := 
    ("test_call", (["x"], ["x"], bedrock_func_body:(
        unpack! p, q  = test();
        x = q
    ))).

    Instance spec_of_call : spec_of "call" := fnspec! "test_call" _x_input_unused ~> x,
    { requires t m := True;
      ensures t' m' := t=t' /\ m=m' /\
        word.unsigned x = 2 }.

Lemma call_correct : program_logic_goal_for_function! test_call.
Proof.
    repeat straightline. straightline_call; auto. repeat straightline; subst; eauto.
Qed.
```

(The variable-name boilerplate is no longer required and we have dropped it e.g. [here](https://github.com/mit-plv/bedrock2/blob/master/bedrock2/src/bedrock2Examples/Demos.v#L8).)
