### ISSUE TITLE
bedrock2 is incompatible with numeral notations

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/bedrock2#23]
I am preparing a PR to fix the code in bedrock2 itself, but please merge https://github.com/mit-plv/bbv/pull/20 and https://github.com/mit-plv/riscv-coq/pull/2 asap and update the submodules in bedrock2.

**Comment by samuelgruetter** [comment]
done: https://github.com/mit-plv/bedrock2/commit/644c991e57fa5fd4e0f2fdd90f4fad37642bc1c0

**Comment by JasonGross** [comment]
Thanks!
