### ISSUE TITLE
Please create a tag for Coq 8.16 in Coq Platform 2022.09

### ISSUE THREAD

**Issue by MSoegtropIMC** [mit-plv/bedrock2#268]
The Coq team released Coq `8.16+rc1` on June 01, 2022.
The corresponding Coq Platform release `2022.09` should be released before **September 15, 2022**.
It can be delayed in case of difficulties until October 15, 2022, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knowledge the latest released version of your project (preview) **does not work** with Coq `8.16+rc1`.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Coq Platform CI (unlike Coq CI) we test only released / tagged versions. Coq CI is currently testing commit 99b86e974bdaf0ed2ffd893b42cf60d980669000 on repository https://github.com/mit-plv/bedrock2 - which likely means that this commit does work in Coq CI.

Could you please create a tag and opam package, or communicate us any existing tag that works with Coq branch v8.16, **preferably before August 31, 2022**?
In case we might have to delay the Coq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

In case the tag and opam package are available before August 17, 2022, it will be included in an early Coq Platform beta release of the for Coq 8.16+rc1.

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.16+rc1~2022.09~preview1`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.16~2022.09~preview1.sh) which already supports Coq version `8.16+rc1` and contains already working (possibly patched / commit pinned) Coq Platform packages.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/274

**Comment by MSoegtropIMC** [comment]
@samuelgruetter @andres-erbsen @JasonGross : I am not sure what to do about this - there are still cross platform issues and possibly others. I had little time to look after this recently (moving homes ...) but we might still be able to get things fixed.

**Comment by andres-erbsen** [comment]
Yeah, I'm not sure what to do here.

- The `sed -z` hack could probably be replaced by `awk '{q=p;p=$0}NR>1{print q}END{ORS = ""; print p}'`
- I don't understand why `Bytedump.v` (which is not autogenerated) is considred a syntax error on Windows (and not on Linux, and not on Windows with coq 8.12).

**Comment by JasonGross** [comment]
The second one can probably be reported as a regression in Coq, attaching a standalone .v file?

**Comment by andres-erbsen** [comment]
I replaced sed with python and checked that it builds on the CI Mac. #273 remains a mystery.

**Comment by MSoegtropIMC** [comment]
I can confirm that this works now on MacOS (and all other platforms except 32 bit Windows - see (https://github.com/coq/platform/issues/178). The version picked is coq-bedrock2.0.0.3 (the only version compatible with fiat-crypto).

So I am closing this as solved.
