### ISSUE TITLE
Less Memory-Hungry, More Principled Solution for Decidable Side-Conditions

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/bedrock2#285]
@andres-erbsen suggests that it is probably decidable side-condition proving at fault for https://github.com/mit-plv/fiat-crypto/issues/1427

This issue tracks having a principled solution to this problem.

> ```
> COQC src/Bedrock/End2End/X25519/GarageDoor.v
> Finished transaction in 46.551 secs (7.101u,0.757s) (successful)
> Finished transaction in 17.874 secs (6.964u,0.165s) (successful)
> Finished transaction in 10.409 secs (7.577u,0.452s) (successful)
> Command terminated by signal 9
> src/Bedrock/End2End/X25519/GarageDoor.vo (real: 1194.29, user: 633.57, sys: 22.09, mem: 3800484 ko)
> ```
> 
> GarageDoor uses too much RAM for Coq's CI. Either we should provide a target that excludes only GarageDoor and it's reverse dependencies, or we should perfomance-optimize GarageDoor.
> 
> https://github.com/coq/coq/runs/8838127340 [coq/coq#16638 (comment)](https://github.com/coq/coq/pull/16638#issuecomment-1275905636)

cc @samuelgruetter

**Comment by andres-erbsen** [comment]
The side-condition I have in mind is that the compiler-emitted instructions fit in 32 bits each.

**Comment by samuelgruetter** [comment]
> The side-condition I have in mind is that the compiler-emitted instructions fit in 32 bits each.

This one should be fixed by https://github.com/mit-plv/bedrock2/commit/335e57a88a41af4ea7394cfaebc803b2945a4d66
