### ISSUE TITLE
Failing in coq CI

### ISSUE THREAD

**Issue by SkySkimmer** [mit-plv/bedrock2#288]
eg https://gitlab.com/coq/coq/-/jobs/3204948208
~~~
COQFLAGS="-Q src/bedrock2 bedrock2 -Q src/bedrock2Examples bedrock2Examples  -Q /builds/coq/coq/_build_ci/bedrock2/deps/coqutil/src/coqutil coqutil " ../etc/bytedump.py bedrock2.PrintListByte.allBytes > special/BytedumpTest.out.tmp
Traceback (most recent call last):
  File "../etc/bytedump.py", line 24, in <module>
    """))
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
Makefile:64: recipe for target 'special/BytedumpTest.out' failed
~~~

**Comment by andres-erbsen** [comment]
Hopefully https://github.com/mit-plv/bedrock2/pull/289 will fix it.

Regardless, is there any chance we can resolve this by bumping the Python version in the Coq CI?

https://docs.python.org/3/library/subprocess.html

>  Changed in version 3.7: Added the text parameter, as a more understandable alias of universal_newlines. Added the capture_output parameter.
