### ISSUE TITLE
Bedrock2 notation breaks record notation

### ISSUE THREAD

**Issue by gmalecha** [mit-plv/bedrock2#29]
After importing Bedrock2 notations, you can no longer write records. The issue seems to be related to the overloading of `;`.

**Comment by samuelgruetter** [comment]
Do you really need to use Coq records and Bedrock2 notations in the same file?

**Comment by gmalecha** [comment]
It would be quite useful to be able to define models using records in the same file as you have code. Of course, this isn't strictly necessary, but breaking a core feature of Coq once you import a library seems like a bad property to have.

We might be able to postpone this until we have custom entries in the parser (Coq 8.9), but another alternative would be to simply replace `;` with `;;` like it is in most notations (e.g. monad notation).

**Comment by samuelgruetter** [comment]
We already use `{{` instead of `{`, so I'd be fine with using `;;` instead of `;`.

**Comment by samuelgruetter** [comment]
Fixed in https://github.com/mit-plv/bedrock2/commit/0b352d402e9870adcc47b0a028c83276de7346ec
