### ISSUE TITLE
Update tested is failing with rate limits

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/bedrock2#309]
https://github.com/mit-plv/bedrock2/actions/runs/3865972183/jobs/6589796901#step:5:9
Error: Invalid repo, token or network issue!
{"message":"API rate limit exceeded for 4.227.0.209. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

**Comment by samuelgruetter** [comment]
Oh noo... So I tried a quick fix, let's hope it's as [easy](https://github.com/samuelgruetter/check-ci-success/commit/2a1807ab13bfed8da1cf8835da980db33c48eebd) [as](https://github.com/mit-plv/coqutil/commit/fc6adcbe7945f9100bd2526005ec225693e3ff02) [this](https://github.com/mit-plv/bedrock2/commit/808fc45afc172b90be67124922f6cf206b8f29a0), we'll see tomorrow when the scripts have run again whether it works.

**Comment by samuelgruetter** [comment]
looks like it's [fixed](https://github.com/mit-plv/bedrock2/actions/runs/3881064926/jobs/6619673987) in [attempt no 2](https://github.com/samuelgruetter/check-ci-success/commit/b9d495e8031cf1a332b8b3df9f78e6bc85a5cb3b)
