### ISSUE TITLE
Bedrock2 is broken on Coq's CI

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/bedrock2#316]
> I've seen bedrock failures on various PRs and master recently, what's going on?
recent master https://gitlab.com/coq/coq/-/jobs/3614185994 "make[3]: Makefile.coq.test: No such file or directory"
last master success https://gitlab.com/coq/coq/-/jobs/3603326579
first master failure https://gitlab.com/coq/coq/-/jobs/3608073924

As recently posted by @SkySkimmer on zulip

This may be a coqutil bug, or a bedrock2/ coqutil interaction bug, or an issue with the targets built by Coq's CI (maybe install gets called in a way that the Makefile is not first created)

**Comment by samuelgruetter** [comment]
Thanks for the notification, hopefully fixed by https://github.com/mit-plv/bedrock2/commit/dafe7142c602c44bf3938b76d479990abfedea18
