### ISSUE TITLE
Unbound value Int.land

### ISSUE THREAD

**Issue by armfazh** [mit-plv/bedrock2#373]
Compilation fails with `Unbound value Int.land` error:

```sh
$ make
...
File "/tmp/fiat-crypto/rupicola/bedrock2/bedrock2/src/bedrock2/ident_to_string.v", line 8, characters 16-24:
Error: Unbound value Int.land

make[3]: *** [Makefile.coq.noex:764: /tmp/fiat-crypto/rupicola/bedrock2/bedrock2/src/bedrock2/ident_to_string.vo] Error 1

```

Running version: commit [b36804f405bde94216630084ca52fc6e177c682b ](https://github.com/mit-plv/bedrock2/commit/b36804f405bde94216630084ca52fc6e177c682b)

**Comment by samuelgruetter** [comment]
Looks like you're using an old Coq version. You need at least 8.16.0

**Comment by armfazh** [comment]
That's correct, I was using coq v8.15. I tried now with 8.17 and works. Thanks.
