### ISSUE TITLE
Please pick the version you prefer for Coq 8.18 in Coq Platform 2023.10 [coq-bedrock2]

### ISSUE THREAD

**Issue by rtetley** [mit-plv/bedrock2#376]
The Coq team released Coq `8.18.0` on September 7th, 2023.
The corresponding Coq Platform release `2023.10` should be released before **November 30th, 2023**.
It can be delayed in case of difficulties until January 15th, 2023, but this should be an exception.

This issue is to inform you that the opam package we are currently testing in Coq Platform CI **works fine** with Coq `8.18.0`.

Coq Platform CI is currently testing opam package `coq-bedrock2.0.0.5`
from official repository https://coq.inria.fr/opam/released/packages/coq-bedrock2/coq-bedrock2.0.0.5/opam. 

**In case this is the version you want to see in Coq Platform, there is nothing to do for you - please just close this issue.**

In case you would prefer to see an updated or an older version in the upcoming Coq Platform `2023.10`, please inform us as soon as possible and before **October 31st, 2023**!

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.18+beta1`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.18+beta1.sh) which already supports Coq version `8.18.0` and contains already working (possibly patched / commit pinned) Coq Platform packages.

In case you want to select a different version, please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/372

**Comment by JasonGross** [comment]
Assuming https://github.com/coq/opam/pull/2805 builds (and fiat-crypto is compatible), please use tag v0.0.6 / to-be-shortly-released coq-bedrock2.0.0.6

**Comment by MSoegtropIMC** [comment]
I updated to coq-bedrock2 version 0.0.6 - fiat-crypto builds with this update.

@JasonGross @rtetley : I cannot close this issue - can you please close it?
