### ISSUE TITLE
all files should Global Unset Refine Instance Mode

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/bedrock2#45]
to get saner behavior on incomplete typeclass instances

also see https://github.com/mit-plv/fiat-crypto/blob/master/src/Util/GlobalSettings.v and https://github.com/mit-plv/fiat-crypto/blob/master/src/Util/FixCoqMistakes.v

@samuelgruetter @stellamplau

**Comment by samuelgruetter** [comment]
I actually like the default behavior, and I'm willing to deal with the inconvenience of "still open proof goals" at the end of sections/modules/files. But thanks for pointing out that this can be changed, that's good to know

**Comment by andres-erbsen** [comment]
FYI you can still get the old behavior by ending the definition with a . (and then `refine`).

**Comment by andres-erbsen** [comment]
this is now default on coq master, so CI will catch us
