### ISSUE TITLE
test 8.9beta in travis

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/bedrock2#48]

**Comment by samuelgruetter** [comment]
I added 8.9-daily (https://github.com/mit-plv/bedrock2/commit/17098641ad6573dd410f08b734bd8a373d378e98) because I couldn't find an 8.9 beta package in @JasonGross' PPA, but probably 8.9-daily is what we want anyways?

**Comment by JasonGross** [comment]
Oops.  There should be an 8.9+beta1 package in an hour or two.  (Build log, e.g., [here](https://launchpad.net/~jgross-h/+archive/ubuntu/many-coq-versions/+build/15770505))

8.9-daily is the tip of the v8.9 branch.

**Comment by andres-erbsen** [comment]
Yes, 8.9-daily is what we want. Sorry for the confusion.
