### ISSUE TITLE
feature request: hex constants

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/bedrock2#53]
from bbv or coq master?

**Comment by andres-erbsen** [comment]
8.9 also has real context free grammar parsing support, so it looks like that's where we're headed anyway

**Comment by andres-erbsen** [comment]
[chacha20](https://github.com/mit-plv/bedrock2/commit/61e70ad6a90d04a04ae7bd6c96c0727c59d2805d) works other than for the hex constants

**Comment by samuelgruetter** [comment]
I have [removed](https://github.com/mit-plv/bedrock2/commit/efc8e691fd7af0c3a3be9c53e2bdcac377e10e77) Coq 8.8 from CI, so feel free to start using Coq 8.9 features :tada: :wink: 

Also, I'd like chacha20 to be on master.

**Comment by samuelgruetter** [comment]
Hex constants in action for MMIO: https://github.com/mit-plv/bedrock2/commit/e77da6b1149f380f3912e9905d1b3005e1424e34

**Comment by samuelgruetter** [comment]
On the other hand, the bbv HexNotations are safer than Coq standard lib, because they return `ParseError` instead of `0` if the string is invalid, so maybe it's better to copy the bbv HexNotations to coqutil?

**Comment by andres-erbsen** [comment]
nah safety from proofs is enough

**Comment by samuelgruetter** [comment]
Except maybe if your toplevel spec says your program outputs `Ox"badstring"`, and your buggy program outputs a value which was initialized to zero but not yet assigned the desired result... But yeah that's kind of unlikely

**Comment by samuelgruetter** [comment]
`Ox` is now available in `coqutil.Z.HexNotation`: https://github.com/mit-plv/coqutil/commit/77feea658ab6f7a846215313c8b820061294b3a3
