### ISSUE TITLE
Please bump submodules

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/bedrock2#58]
Since [mit-plv/coqutil#2](https://github.com/mit-plv/coqutil/pull/2) and [mit-plv/riscv-coq#6](https://github.com/mit-plv/riscv-coq/pull/6) have been merged.  This will help with the build on Windows.

**Comment by samuelgruetter** [comment]
done in https://github.com/mit-plv/bedrock2/commit/53a699a0fd5f5621537e03e35da360e7a28b711c

**Comment by JasonGross** [comment]
Thanks!
