### ISSUE TITLE
RFC: object-language structs

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/bedrock2#6]
- one Inductive for the fields of each record, with the constructors representing field names
- each field name is interpreted as an offset into the struct
- all fields are disjoint by construction
- ABI-compatible with gcc/llvm [`__attribute__ ((__packed__))`](https://gcc.gnu.org/onlinedocs/gcc-4.0.4/gcc/Type-Attributes.html). this is probably trivially true right now but would be important if new types are added
- notations TBD, C-style

**Comment by samuelgruetter** [comment]
I think this could (and should) be achieved without any* changes to `ExprImp.v`: Just make a new file containing some Gallina definitions which expand to existing `ExprImp` constructs. Do you agree?

*) except maybe `SLoad` and `SStore` with an offset.

**Comment by andres-erbsen** [comment]
yep, no changes to `ExprImp`, just a convention.

**Comment by samuelgruetter** [comment]
sounds good to me!

**Comment by andres-erbsen** [comment]
`bedrock2.Structs`
