### ISSUE TITLE
build bedrock2 semantics separately from the compiler

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/bedrock2#8]
We should make sure tools/code for the bedrock2 language is easy to use, and given the current build time of riscv-semantics, it would probably be a good idea to support requiring bedrock2 semantics without the compiler. Two options would be splitting the repository more and adding a separate makefile target, there probably are more.

**Comment by samuelgruetter** [comment]
I agree! I think a separate makefile target is the way to go, I'll give it a shot this morning.

**Comment by samuelgruetter** [comment]
Ok so I did a bit of refactoring and added a Makefile target called `ExprImp`, so now you should be able to do what I just added to the REAMDE:

To build only the source language (ExprImp):
*    run `make` in the `bbv` directory
*    run `make util` in the `riscv-coq` directory
*    run `make ExprImp` in the `bedrock2` directory

Please let me know if it works (or if I screwed something up :wink:).

**Comment by andres-erbsen** [comment]
why does exprimp depend on riscv-coq at all?

**Comment by samuelgruetter** [comment]
Both ExprImp and riscv-coq need some general utility stuff such as monads and a bitwidth typeclass, and I don't want to duplicate this utility code. Currently, this utility code lives in `riscv-coq/src/util`. I could move it into a separate repo, but I don't think this would add any value.

**Comment by andres-erbsen** [comment]
I tried factoring the semantics out further. Please review https://github.com/mit-plv/bedrock2/commit/d4ab29a0a4e405a98503d836926a193a8baf91c6 for style and not semantics and give me feedback on whether you think this is a good direction.

**Comment by andres-erbsen** [comment]
(Stalled on https://github.com/coq/coq/issues/7892, thinking about how to proceed.)

**Comment by andres-erbsen** [comment]
This works now.
